### ISSUE TITLE
Window title color when using Web Apps

### ISSUE THREAD

**Issue by ciro-mota** [daniruiz/flat-remix-gtk#100]
Hello. When using a Web App generated with Chrome, the title of the windows is given a gray color that makes it almost impossible to read. Is it possible to adjust the theme to suit that part of the window or does it depend on Chrome settings?

**Comment by daniruiz** [comment]
Could you provide a screenshot?

**Comment by ciro-mota** [comment]
Thank you! Of course, follow the print you requested. Note that the window title and Chrome buttons are the same color.

[Imgur](https://imgur.com/c9qjueB)

**Comment by daniruiz** [comment]
Sorry, but that is Chromes fault. The theme only sets the background for the normal window. If chrome changes it there is nothing I can do
