### ISSUE TITLE
pcmanfm keyboards shortcuts stopped working

### ISSUE THREAD

**Issue by sidmint** [daniruiz/flat-remix-gtk#102]
I'm on Mint 19.3 xfce. Pcmanfm keyboard shortcuts stops working when I switch to green-darkest version of theme style [not icon theme] [may be true for other versions too]. Thunar and nemo continue to work fine.
Why is this happening? What conf I must do to fix it? Can this be fixed in future release.

examples of lost shortcuts:
.key m to remove pcmanfm bookmark from side pane after right click
.key h to 'extract here' from context menu in pcmanfm
.these are just few examples, I am experiencing that no shortcuts for context menu is working

Btw, this is the best darkest variant of style I have found in the world as of now, THANKS A TON.

![1](https://user-images.githubusercontent.com/43943312/90064229-15984900-dd08-11ea-9f7d-4b92a90526cd.gif)

**Comment by daniruiz** [comment]
Hi there!
thanks for the feedback, but there's no way the theme can change how shortcuts work. Sorry but that has to be something else

**Comment by sidmint** [comment]
Thanks for looking into the issue, I think I got your point but how to explain the fact that this issue doesn't happen with other themes like mint-x, mint-y, Adwaita, xfce, Windows-10-Acrylic dark to name just a few?
