### ISSUE TITLE
invisible xfce4-timer-plugin in darkest variant

### ISSUE THREAD

**Issue by sidmint** [daniruiz/flat-remix-gtk#103]
xfce4-timer-plugin is invisible on the panel [total black] in darkest variant in inactive state ie when timer isn't running.
I use green darkest, Mint 19.3 xfce.

**Comment by daniruiz** [comment]
I'm closing this issue as it is old and all the themes have been completely redesigned.
If the issue persists, even with the new themes, feel free to reopen it.
