### ISSUE TITLE
No support for apps installed via snap. 

### ISSUE THREAD

**Issue by KyleBroflowski** [daniruiz/flat-remix-gtk#105]
I've installed apps like libreoffice via snao install. But these apps are still in the defuakf adwaita théme even after the Flat Remix is applied. This is a real issue. I like dark themes and the adwaita is blindeningly white. 
I read that  if you use a GTK theme NOT included in the Snap theme bundle gtk-common-themes, it will lead to similar issues. 
Please include this awesome theme also into gtk-common-themes snap package

**Comment by jollygoose** [comment]
Hello, I hope this an appropriate place to put this. I've made a [snap](https://github.com/jollygoose/flat-remix-gtk-snap) of the flat-remix-gtk latest release. All the themes are bundled under a single snap. I don't mind looking at putting this on the snap store if that is alright (and if things like the license and everything else looks correct).

The flat-remix icon theme has also been [snapped](https://github.com/jollygoose/flat-remix-snap)

**Comment by daniruiz** [comment]
Hi!
Thank you for your contribution, feel free to package and publish it in the store. That helps me a lot :wink:

**Comment by jollygoose** [comment]
Alright cool, they have been added to the snap store: [gtk](https://snapcraft.io/flat-remix-gtk), [icons](https://snapcraft.io/flat-remix). And thanks for the awesome theme.

**Comment by daniruiz** [comment]
Awesome. Can this issue be closed then?

**Comment by jollygoose** [comment]
Yes, I believe so.
