### ISSUE TITLE
White title bars on maximized windows with Darkest variants in Cinnamon

### ISSUE THREAD

**Issue by isfalcantara** [daniruiz/flat-remix-gtk#106]
OS: Manjaro 20.2
DE: Cinnamon

In Cinnamon, the title bars become completely white on maximized windows when using the **Darkest** variants that **have a border**, like `Flat-Remix-GTK-<Any color>-Darkest` or `Flat-Remix-GTK-<Any color>-Darkest-Solid`. I used GNOME for many months before migrating to Cinnamon, never encountering this issue.

Normal window:
![normal_window](https://user-images.githubusercontent.com/11619375/99807362-313c9800-2b1e-11eb-844d-ce2431372399.png)

Maximized window:
![maximized_window](https://user-images.githubusercontent.com/11619375/99807384-3ac60000-2b1e-11eb-825e-21c9244dd18a.png)

**Comment by TotallyNotLime** [comment]
I have the same issue with elementary

**Comment by daniruiz** [comment]
The old darker theme is no longer supported
