### ISSUE TITLE
White line around the windows (Elementary)

### ISSUE THREAD

**Issue by TotallyNotLime** [daniruiz/flat-remix-gtk#108]
Hi!
I installed the darkest theme in elementary (5.1.7) but i see a white line around the windows.[
![Képernyőkép erről: 2020-12-26 15-18-38](https://user-images.githubusercontent.com/76620411/103153072-0e8d4700-478e-11eb-83ec-d19b96463f7a.png)
![Képernyőkép erről: 2020-12-26 15-18-46](https://user-images.githubusercontent.com/76620411/103153074-0fbe7400-478e-11eb-88b4-6faa770a481d.png)

**Comment by KushagraKarira** [comment]
The theme has border and non-border variants, change the theme
`gsettings set org.gnome.desktop.interface gtk-theme Flat-Remix-GTK-Blue-Darkest-Solid-NoBorder`
to remove border, same can be done in the tweaks app
