### ISSUE TITLE
Some Buttons have Black Bars inside of them ....

### ISSUE THREAD

**Issue by black1good** [daniruiz/flat-remix-gtk#109]
![Screenshot from 2021-01-08 16-55-55](https://user-images.githubusercontent.com/23730046/104043657-6ab78880-51dc-11eb-96cf-1d6cb31afe21.png)
Hi ,
As you can see there is something black in this blue search button , i don't know how to change it or to make it better .
Im my POP Shop Home and Installed Buttons is same thing , there is something black inside them , i don't know what the problem is but i am open to make it better . 
My System : 
Pop!_OS 20.10
Gnome: 3.38.1
Windowing System : X11

**Comment by daniruiz** [comment]
I'm closing this issue as it is old and all the themes have been completely redesigned.
If the issue persists, even with the new themes, feel free to reopen it.
