### ISSUE TITLE
GTK4 support?

### ISSUE THREAD

**Issue by sp1ritCS** [daniruiz/flat-remix-gtk#112]
I'm wondering if Flat Remix will support gtk4, now that is has been released?

Is this something you are working on it, or are there no docs yet that would allow you to start working on it?

**Comment by maydayv7** [comment]
Now that GNOME 40 using GTK 4 is released, more emphasis will be laid on this

**Comment by Hikandy** [comment]
Is there work being done on to support gtk4?

**Comment by daniruiz** [comment]
Finally done! :tada: 

https://github.com/daniruiz/flat-remix-gtk/commit/a98034b90292a198118a74bdbe3dd60aba4a5592
https://github.com/daniruiz/flat-remix-gtk/commit/690cf8b7024f9a56c9468d61cade77bdf7433ad9
https://github.com/daniruiz/flat-remix-gtk/commit/9f2e3b2a00b412f5a4796b03dd63a15efe0b732f
