### ISSUE TITLE
Flat-Remix-Darkest shell theme has low contrast text for non-highlighted text in context menu

### ISSUE THREAD

**Issue by toxicmender** [daniruiz/flat-remix-gtk#113]
![Screenshot from 2021-03-06 18-18-26.png](https://user-images.githubusercontent.com/13049649/110207365-0a298c80-7ea9-11eb-8807-5d319347b4c0.png)

![Screenshot from 2021-03-06 18-18-34.png](https://user-images.githubusercontent.com/13049649/110207369-11509a80-7ea9-11eb-8aa0-b1acbf178d7f.png)

as visible in the screenshots, the name of the wifi when not highlighted turns completely black.

Although I haven't been able to screenshot it, there is also a bug where nautilus darkens the icons so dark that they become invisible against the dark theme when you right click on the icon. 

I'm using Flat Remix GTK Blue Darkest Solid no Border for applications and Flat Remix Darkest Full Panel for shell theme.

I'm using GNOME
![Screenshot from 2021-03-06 18-59-43.png](https://user-images.githubusercontent.com/13049649/110209549-364a0b00-7eb3-11eb-9738-7ad832eb5c8f.png)

I hope this gets resolved soon.

**Comment by daniruiz** [comment]
I'm closing this issue as it is old and all the themes have been completely redesigned.
If the issue persists, even with the new themes, feel free to reopen it.
