### ISSUE TITLE
Issue with Firefox 87 and Proton

### ISSUE THREAD

**Issue by sergioad** [daniruiz/flat-remix-gtk#114]
With Firefox maximized there is a black bar on top
![Captura de pantalla de 2021-03-25 23-53-16](https://user-images.githubusercontent.com/5375145/112589358-8d624200-8dc6-11eb-8562-a9154eb8e613.png)

**Comment by Everest10** [comment]
Same problem here using flat remix window decoration gtk darkest + cinnamon and fedora 34. There is a bug in the window decoration.
