### ISSUE TITLE
Some findings and advice

### ISSUE THREAD

**Issue by fighuass** [daniruiz/flat-remix-gtk#115]
I've been using the theme for a bit now and it looks really great! Definitely one of the best themes I've seen yet.

But I noticed a few issues that I'd like to bring to your attention, alongside some advice on how to fix these:

1: When a window is not in focus, the window buttons (minimize, maximize, close) become grey. Not a problem in itself, but they all have the exact same shade, which looks a bit strange.

![buttonsunfocus](https://user-images.githubusercontent.com/28998263/112817802-5ca63500-9072-11eb-9df0-a0272ad2561c.png)

I'd change it to be more like this:

![buttonsunfocusmockup](https://user-images.githubusercontent.com/28998263/112818001-937c4b00-9072-11eb-9377-388af1f8e344.png)

2: There's quite a big gap between the dock and maximized programs.

![gap](https://user-images.githubusercontent.com/28998263/112818369-fb329600-9072-11eb-962e-01aa4a8b5293.png)

I'm not sure if this is intentional or not, but if it is I would encourage adding a separate version of the theme that doesn't have this gap (it looks a little buggy to me).

3: This could be a me issue, not sure (doesn't show up in the default Ubuntu theme though), but I notice a sort of aliasing in certain UI elements.

For example, notice the left and right sides of the search bar:

![searchbar](https://user-images.githubusercontent.com/28998263/112818722-5a90a600-9073-11eb-85c3-6325756071ac.png)

Or how jagged this icon looks:

![progressicon](https://user-images.githubusercontent.com/28998263/112818909-90358f00-9073-11eb-9f35-91c692ead8ab.png)

Other similar UI elements have this too.

4: I think this is for the shell theme but I'll add it here. Very minor thing, but when I hover my mouse over the right tray (internet, volume, microphone, power button), the hover animation is much faster than the hover animation of the other top bar items like activities, programs, clock, etc.

Anyways, great theme!

**Comment by daniruiz** [comment]
I'm closing this issue as it is old and all the themes have been completely redesigned.
If the issue persists, even with the new themes, feel free to reopen it.
