### ISSUE TITLE
Issue Firefox 87 and Flat Remix Window Decoration GTK Darkest + Cinnamon and Fedora 34

### ISSUE THREAD

**Issue by Everest10** [daniruiz/flat-remix-gtk#116]
When the user try to hide the Firefox 87 title bar there is a bug related Flat Remix Window Decoration GTK Darkest. There is a black gap between the tabs border and the screen border.

DE: Cinnamon 4.8.6
OS: Fedora 34 64 bit

![maim-Screenshot from 2021-04-23 20-18-24](https://user-images.githubusercontent.com/7228207/115937553-a403c380-a46e-11eb-993d-b20144826bf5.png)

**Comment by daniruiz** [comment]
I'm closing this issue as it is old and all the themes have been completely redesigned.
If the issue persists, even with the new themes, feel free to reopen it.

**Comment by TheFirstQuestion** [comment]
Can confirm that the issue persists. I'm on Mint 19.1, Cinnamon 4.0.10, Firefox 94.0. It's happening for me no matter which flavor of Flat Remix I choose. (See top of screenshot)

![image](https://user-images.githubusercontent.com/16431286/143132212-da7fe632-593e-48ef-a937-74da287713e8.png)

Please let me know how I can be most helpful! Thanks for all you do :D

**Comment by daniruiz** [comment]
This is fixed now with the latest version.
Thank you for reporting ;)
