### ISSUE TITLE
Sidebar and file view space of Thunar appear dark when using a light GTK theme

### ISSUE THREAD

**Issue by samueldy** [daniruiz/flat-remix-gtk#118]
First off, excellent work with this theme! I just discovered this the other day and am amazed!

I just had a small issue with using the light GTK themes in XFCE4. I installed the themes from the flat-remix-gtk 20201129-1 AUR package and am using the Flat-Remix-GTK-Yellow (light) theme. Most GTK controls look just fine, but in Thunar (4.16.6), the sidebar and space where files are displayed still appear dark. I'm not sure if this is an Arch bug, but I'm wondering if you know why this could be happening:

![image](https://user-images.githubusercontent.com/43612797/117583839-b153bb80-b0c6-11eb-8bee-14f066cf067a.png)

I'm on XFCE 4.16, and all system packages and Flat Remix AUR packages are up to date.

Edit: have tried killing and restarting both all `thunar` processes and `Thunar --daemon`.

Thanks,
-- Sam

**Comment by daniruiz** [comment]
I'm closing this issue as it is old and all the themes have been completely redesigned.
If the issue persists, even with the new themes, feel free to reopen it.

**Comment by samueldy** [comment]
Sorry, had forgotten about this issue. Yes, I downloaded the New version of the thing, and everything looks great!
