### ISSUE TITLE
How to Create your own variant?

### ISSUE THREAD

**Issue by leier69** [daniruiz/flat-remix-gtk#119]
Hi! Im kind of a noob, and could not find anything from googling. I see that there is a build.sh file in src folder. Does that mean its possible to create a theme with a custom color? cause I really wanna change the background and highlight color abit to match my i3 setup.

Please give me some instructions if this is possible :sweat_smile:

**Comment by daniruiz** [comment]
Download the `master.zip` package and extract it.
Inside it run:

./generate-color-theme.sh VARIANT_NAME HIGHLIGHT_HEX_COLOR HIGHLIGHT_TEXT_HEX_COLOR


Example:

./generate-color-theme.sh FOOBAR '#123456' '#987654'
