### ISSUE TITLE
Disable app menu button

### ISSUE THREAD

**Issue by sp1ritCS** [daniruiz/flat-remix-gtk#121]
Hi, I'm currently working on an Gtk+3 application and I'm working to integrate a global app menu.
The appmenu button in the HeaderBar looks fine with Adwaita, however Flat-Remix-GTK sets the opacity of the image to zero and makes it so that the button looks like the min/max/close buttons.

https://github.com/daniruiz/flat-remix-gtk/blob/811159c82498d0e77e4351b4177df9bf4b05958e/src/sass/gtk-sass/_common.scss#L3902

Can you add a way for applications to disable this behaviour (by adding a custom class to either MainWindow or HeaderBar) that makes the appmenu button look like a regular button in the HeaderBar (like the ones added by `gtk_header_bar_pack_start/end(`)?

**Comment by daniruiz** [comment]
Hi!
Could you provide a screenshot of the issue for both Adwaita and flat-remix theme, I'm not sure about what type of buttons are affected.

**Comment by sp1ritCS** [comment]
Sure,
![Screenshot from 2021-06-03 23-47-53](https://user-images.githubusercontent.com/31540351/120716318-28ae1c80-c4c6-11eb-9db6-b8ce585c655b.png)
![image](https://user-images.githubusercontent.com/31540351/120716259-1338f280-c4c6-11eb-893d-f4efd31ad8e6.png)

**Comment by daniruiz** [comment]
This should be fixed now with the new version
