### ISSUE TITLE
GTK4 package for Fedora

### ISSUE THREAD

**Issue by tommytran732** [daniruiz/flat-remix-gtk#122]
Hi,

I noticed that Flat-Remix has a GTK2 and 3 package for Fedora, however there seems to be no GTK 4 package. I wonder if you could add a package for it to either the COPR or main repo?

![image](https://user-images.githubusercontent.com/57488583/119744595-58bc4680-be5a-11eb-9eaf-5224781811a2.png)

**Comment by daniruiz** [comment]
I'm currently working on the gtk4 theme for Skeuos-GTK and I plan to use that code as a base for flat-remix-gtk in the future. The code of flat-remix is far from perfect :laughing: and it's became hard to maintain

**Comment by Kerrung** [comment]
@daniruiz have you any news about GTK4 port?

**Comment by telometto** [comment]
> @daniruiz have you any news about GTK4 port?

@daniruiz Seconding this. Very nice themes, btw!

**Comment by daniruiz** [comment]
Already working on it. Right now it includes the gtk4 themes from skeuos, as all the code is now based on that theme

**Comment by daniruiz** [comment]
Duplicated
https://github.com/daniruiz/flat-remix-gtk/issues/112
