### ISSUE TITLE
No darker and darkest themes

### ISSUE THREAD

**Issue by BxOxSxS** [daniruiz/flat-remix-gtk#128]
Just updated aur package and I see new variants but all without darker or darkest 
Why such decision? Are there plans to add them? I mostly used this theme for these variants so please add them back

**Comment by daniruiz** [comment]
The themes have been completely redesigned and the new version does not support darker and darkest variants yet.
I was avoiding updating the package cos I knew this would happen, but then people were marking my packages as obsolete :( so I gave up and updated them.

Previous themes have not been removed, they are inside the folder themes-old in this repository

**Comment by bruhtus** [comment]
I want to ask, there's a plan to support the darkest variants right?
I mean, one of the distinguish feature of flat remix was the darkest variants and that would be sad if the darkest variants disappear from flat remix.

**Comment by daniruiz** [comment]
Yes, I do plan to add darkest variants and I'm already working on darker variants. I just didn't have the time
But they are not removed, you can still download them from the themes-old folder
