### ISSUE TITLE
Missing Darkest (and Darker)

### ISSUE THREAD

**Issue by genofire** [daniruiz/flat-remix-gtk#130]
after updating this very beautiful themen was removed ;(

**Comment by daniruiz** [comment]
https://github.com/daniruiz/flat-remix-gtk/issues/128

**Comment by genofire** [comment]
hmm, okay duplicated - but  they does not answer if there would be support again
...

**Comment by daniruiz** [comment]
> Yes, I do plan to add darkest variants and I'm already working on darker variants. I just didn't have the time
But they are not removed, you can still download them from the themes-old folder
