### ISSUE TITLE
can't see anything in Oracle Virtual Box application

### ISSUE THREAD

**Issue by notokrs** [daniruiz/flat-remix-gtk#131]
Hello Dani!, thanks for fixing #129 but i found another issue in Oracle Virtual Box. I currently use the new version of Flat Remix Yellow (211123) and i cant see anything in Virtual Box. I think because it's appear as white text (?)

![2021-11-24_10-39](https://user-images.githubusercontent.com/79308398/143171785-727ef3e6-c9ff-456c-9d80-227e8586a14f.png)

**Comment by daniruiz** [comment]
That makes no sense. Virtualbox is qt not gtk.
Are you using the gtk2 theme engine for qt, check in qt5ct

**Comment by notokrs** [comment]
yeah, i'm already set gtk2 theme in qt5ct. but another qt5 app is normal like qbittorent.

![2021-11-27_05-44](https://user-images.githubusercontent.com/79308398/143659573-ec480407-87d1-4563-9cba-de472f7ee6bb.png)

even other parts of the virtual box itself are normal, it only happens on the dashboard

![2021-11-27_05-52](https://user-images.githubusercontent.com/79308398/143659816-ad6926bd-38e9-4336-95e4-9e681f96bfb4.png)
