### ISSUE TITLE
Conflicts packages

### ISSUE THREAD

**Issue by discover02** [daniruiz/flat-remix-gtk#134]
Hello, I have added the copr repo of the theme you have made to my system. But when I wanted to install the theme completely, I realized that flat-remix-theme and flat-remix-gtk theme were dependent on each other and later conflicted.

![image](https://user-images.githubusercontent.com/62564400/147812142-d56b62fb-5ce9-4d71-8655-775d0d054f4b.png)

**Comment by daniruiz** [comment]
you are installing the package flat-remix-theme, which is not part of my copr but an official package from fedora that contains the gtk themes too.

https://src.fedoraproject.org/rpms/flat-remix-theme

**Comment by discover02** [comment]
I thought you supported this when I saw the .spec files in your Github repo

**Comment by daniruiz** [comment]
I do, but my theme package for gtk is called `flat-remix-gtk`, the icon theme `flat-remix` and the gnome theme `flat-remix-gnome`
No `flat-remix-theme`
