### ISSUE TITLE
No more border in active window

### ISSUE THREAD

**Issue by artu72** [daniruiz/flat-remix-gtk#135]
Hi, after upgrading to 0.0.20211223 version in Fedora 35, active windows do not show white borders as before. I use system packaged version of flat-remix, Flat-Remix-GTK-Blue-Darkest-Solid variant.

**Comment by daniruiz** [comment]
Hello!
That theme variant was from the old version. Unfortunately while remaking the whole theme I could not add that one and the darker one as they were complicated to maintain and my time is way more limited right now.
You can still download the old themes from this folder https://github.com/daniruiz/flat-remix-gtk/tree/master/themes-old
