### ISSUE TITLE
Both light and dark versions use black font for desktop icons

### ISSUE THREAD

**Issue by drws** [daniruiz/flat-remix-gtk#138]
I'm using a light version of the theme with Xfce and for one find the dark (black?) desktop icon font hard to read, even with brighter backgrounds. Since it's a "light" theme a brighter (white or near-white) font would be more appropriate in my opinion.

Similar with the -dark* versions of the theme. There is a high chance that user preferring a dark theme will also use a dark background for which the dark font color is inappropriate.

Is the font color deliberately dark/what is the reasoning?

**Comment by daniruiz** [comment]
Fixed https://github.com/daniruiz/flat-remix-gtk/commit/d719ad7322324358fc84f4df7948680057870bc1
