### ISSUE TITLE
Blue border around search bar in Google Chrome GTK+

### ISSUE THREAD

**Issue by patri9ck** [daniruiz/flat-remix-gtk#140]
https://i.imgur.com/EbZI9QD.png

A blue border is put around the search bar when the Green Dark theme is being used in Google Chrome. I use version 20220427-1 provided by the AUR.

**Comment by daniruiz** [comment]
Confirmed, thanks for reporting.
Will try to fix it today :wink:

**Comment by patri9ck** [comment]
Thank you very much. It seems to be fixed. Keep up the great work :)
