### ISSUE TITLE
Text on Buttons in Trash Folder not readable

### ISSUE THREAD

**Issue by FineFindus** [daniruiz/flat-remix-gtk#142]
The text on the buttons in the trash folder is not readable, when using the light theme.

![grafik](https://user-images.githubusercontent.com/63370021/169323637-0ef0df54-bf3f-40c1-9deb-0ebda01f1dbe.png)

**Comment by daniruiz** [comment]
What program are you using?

**Comment by FineFindus** [comment]
This is Nautilus 42.1.1 on Ubuntu 22.04 in the trash folder. 
![image](https://user-images.githubusercontent.com/63370021/173754676-2f4396ec-a16f-44cf-a88e-e4670893c4f5.png)

**Comment by FineFindus** [comment]
Hmmm. I just tried to reinstall, using the newest release (20220527) with the `Flat-Remix-GTK-Blue-Light`. The issue still persist on Ubuntu 22.04. Interestingly enough, I am unable to replicate it on my Arch install, where it has the same orange bar as shown in your screenshot.
