### ISSUE TITLE
Yellow progress bars not readable in light theme

### ISSUE THREAD

**Issue by drws** [daniruiz/flat-remix-gtk#143]
The yellow-colored theme's progress bars such as the one in volume popup on volume change in Xfce are not clearly seen on light background. It's arguable this is the desired output, but to make this (and possibly some other) color-background combinations really usable, some coloring rules probably need to be broken/adjusted to include colors with more contrast between them.

**Comment by daniruiz** [comment]
Buf, it's true but I don't really know if this can even be fixed without changing the accent color.
My recommendation would be to use the dark variant with the yellow theme, otherwise trying to fix this would be super complicated :(
sorry
