### ISSUE TITLE
Uneven border on Gnome terminal.

### ISSUE THREAD

**Issue by simurgh9** [daniruiz/flat-remix-gtk#144]
This maybe a legacy/non-legacy app issue. The windows from bottom are Gnome terminal, Gnome text-editor, Nautilus and Emacs. 

![borders](https://user-images.githubusercontent.com/43047754/172029186-7e51f5db-03bb-466b-8b8c-872cf45c2d97.png)

Observe the different width of vertical and horizontal borders on the Gnome terminal. They are also a bit wider and different colours than other applications' borders. I would not fuss about it that much but I use the terminal quite a bit and this is like a tiny speck of dust in my eye.

I'll appreciate if anyone could help me fix this.

I'm on Debian GNU/Linux `bookworm/sid` with Gnome 42.

**Comment by daniruiz** [comment]
That can't be fixed sorry. The GTK4 app uses its own border and doesn't get affected by the theme.
Then for some GTK3 apps I added a thicker bottom border to be able to have the rounded bottom corners, but as gnome-terminal uses a different background you can see that border.
And then non GTK apps just don't have rounded borders.

In arch you can install [mutter-rounded from AUR](https://aur.archlinux.org/packages/mutter-rounded), which includes a patch that forces all corners to be equal.
