### ISSUE TITLE
Window button icons not showing in libadwaita apps

### ISSUE THREAD

**Issue by ArtyIF** [daniruiz/flat-remix-gtk#146]
When hovering over icons in libadwaita apps, the icons don't show up. Examples:

GNOME Terminal 3.44.1, uses GTK 3:
![icon shows up when hovering over](https://user-images.githubusercontent.com/8017858/174070086-011ecef7-9bf9-4b6f-a979-43e054ec7c75.png)

GNOME Settings (GNOME 42.2), uses libadwaita:
![icon does not show up when hovering over](https://user-images.githubusercontent.com/8017858/174070186-2d2b5675-7360-4204-8928-29d0b8bd1877.png)

**Comment by daniruiz** [comment]
You probably didn't copy the assets folder
