### ISSUE TITLE
What did you do!?!?

### ISSUE THREAD

**Issue by Old-Knitterhemd** [daniruiz/flat-remix-gtk#15]
Why is the dark theme all black?

Why are there white borders?

Why did you change it?
Looks awful...

https://i.imgur.com/vk0fa4Z.png

**Comment by bicodegas** [comment]
I'm using xfce and this change doesn't work either. I don't have the white borders (maybe because there's no Flat Remix xfwm theme, I was using Arc's) but almost pitch black seems is too much. Please, think it through...
Thanks for you work,
Cheers

**Comment by daniruiz** [comment]
I've uploaded the new version with the previous dark colors as Flat-Remix-Dark and moved the "full black" version to Flat-Remix-Darkest.
![image](https://user-images.githubusercontent.com/12565871/47898359-db80ee80-de75-11e8-8a68-4ad2745f2adc.png)

**Comment by Old-Knitterhemd** [comment]
Thank you very much!
It's highly appreciated!!!
