### ISSUE TITLE
Dark colors too dark on some screens

### ISSUE THREAD

**Issue by drws** [daniruiz/flat-remix-gtk#150]
First of all, we're talking about colors, so this one definitely is subjective.

I'm using Xfce + Flat Remix with different setups and I've noticed that on some of screens I use both dark options are simply too dark. I think there is need for a bit lighter dark version as well.

I know this is probably a common request and that the list of theme variants is already long with all the possibilities (discussion about possible solutions in #149). On the other hand I hope we can agree that current variants are all very bright or very dark and that maybe there is a need for a variant between these extremes.

**Comment by daniruiz** [comment]
Sorry but I can't create more variants. It would make the theme really hard to maintain.
I've tried in the past to make the theme look less dark, but unless I make it gray there's always going to be someone complaining about it. The theme being so dark is what makes it different
