### ISSUE TITLE
Theme does not style Chromium-based GTK4 file-chooser?

### ISSUE THREAD

**Issue by fsevenm** [daniruiz/flat-remix-gtk#154]
It seems like the theme does not apply to chromium and google chrome file chooser dialog, it looks like this:
![image](https://user-images.githubusercontent.com/29963765/228411805-90789692-a4cb-4c09-8293-7c54465db5a9.png)

For comparison, this is the one shown by firefox:
![image](https://user-images.githubusercontent.com/29963765/228412007-fa7a48bf-3722-471c-9871-30964a76fcdc.png)

I am not sure if this is due to the chromium/chrome does not pick up the theme or from the theme one. But what I know so far they are using GTK4 file-chooser dialog.

**Comment by fsevenm** [comment]
I may not understand about GNOME is switching to use libadwaita for its applications, which does not take my gtk4 configs. But, I did find a [useful post](https://bbs.archlinux.org/viewtopic.php?pid=2030448#p2030448) to force it using specific them other than default theme Adwaita.

**Comment by daniruiz** [comment]
This is now solved. The theme supports libadwaita themes
