### ISSUE TITLE
Google Chrome title bar has the same color for everything

### ISSUE THREAD

**Issue by gnolooo** [daniruiz/flat-remix-gtk#156]
Hi, after last update, Google Chrome with Flat Remix has now no distinction between elements' colors in title bar. I believe it's just something like 2 colors supposed to be different but they are not. In fact, there are at least 5 elements which should have different colors: active tab, inactive tabs (which should be the same as title bar background), tab when hovering with mouse, dropdown arrow for tabs searching (on the right) and tab separator (the little vertical bar that separates tabs, you can see it between extensions button and labs/cast/download/profile buttons, at the right of search bar).

Here is a screenshot (as you can see I also have the pointer to show hovering has the same color too):
![image](https://user-images.githubusercontent.com/76843243/236237038-5e395599-d72a-4249-9a2b-f5d996389ca3.png)
This does not happen when using classic theme, Qt theme or custom Chrome Web Store themes (you can clearly see the difference between tab with mouse hovering, active tab, inactive tab, dropdown tab search arrow and tab separator):
![image](https://user-images.githubusercontent.com/76843243/236237293-25d2dde3-5eb9-488a-8e1b-489b6c5f148e.png)
![image](https://user-images.githubusercontent.com/76843243/236238007-90378a79-c2a3-4d14-85a4-ae1c9a51d356.png)
![image](https://user-images.githubusercontent.com/76843243/236238239-56394ca9-61a5-45b0-8c80-8ab7fc9991ff.png)

This should be stupidly easy to fix, but I don't know where to put my hands in theme files (searching for color code `#23252e` inside gtk.css gives me 70 matches... 0 idea which one is the right one).

**Comment by daniruiz** [comment]
I can't control chrome's theme sorry. Chrome uses some styles and colors from the theme but I can't modify them. It would require creating a theme for chrome
