### ISSUE TITLE
Firefox titlebar left buttons layout issue

### ISSUE THREAD

**Issue by 2Kelvin** [daniruiz/flat-remix-gtk#158]
Hello @daniruiz. I absolutely love your flat-remix-theme. I just wanted to provide some more information on the issue. The buttons work perfectly when the button layout is on the right side, however when I switch this layout to the left side, most apps work fine but my firefox-esr breaks. Here's a snippet:

![flatremix-issue](https://github.com/daniruiz/flat-remix-gtk/assets/85868026/09c28156-523a-4a35-b9eb-77c3f2ca5a83)

 I'm using Ubuntu Budgie 22.04.3 LTS.
 
 Just want to again say that I appreciate you for your amazing work.

**Comment by daniruiz** [comment]
Duplicated https://github.com/daniruiz/flat-remix-gtk/issues/147
