### ISSUE TITLE
Large windowcontrols for GTK4/LibAdwaita apps

### ISSUE THREAD

**Issue by Pranay-Chopra** [daniruiz/flat-remix-gtk#159]
The new update is great. Thank you dani. But as the title says, here you go:
![image](https://github.com/daniruiz/flat-remix-gtk/assets/66022696/ff2191c8-c99f-4edd-b3b7-5b06c8d92223)

also have a look at the side panels. since the theme is darkest, they should be completely black, am i right?:
![image](https://github.com/daniruiz/flat-remix-gtk/assets/66022696/01642683-1a51-4133-8b58-ac78246b7e4d)

The theme is Flat-Remix-GTK-Green-Darkest-Solid. The issue is only for GTK4 apps

**Comment by siddhpant** [comment]
> The new update is great.

Which new update? Is there any other channel?

**Comment by daniruiz** [comment]
The new theme updates should fix those issues
