### ISSUE TITLE
Menubar color on GTK2 dark theme

### ISSUE THREAD

**Issue by RixzZ** [daniruiz/flat-remix-gtk#16]
Hello.

First of all, I love the new dark theme. I see that you just updated the GTK2 theme which made the QT4/5 apps that can use a GTK theme look great again.

In someapps, the menubar is still using the old color. Screenshot:
![screenshot from 2018-10-24 02-44-15](https://user-images.githubusercontent.com/1339272/47398972-d36ad580-d736-11e8-9098-2854ab97579f.png)

In qBittorrent, which is QT5, the theme is obtained from GTK2 theme, so maybe there is a bug in that version.

Is that fixable or maybe a problem about how QT reads the GTK2 theme?

Thanks!

**Comment by daniruiz** [comment]
It is fixed now. Thanks, I didn't notice!

**Comment by RixzZ** [comment]
Thanks for the update.

There seems to be a difference in the menubar color between the gtk3 and gtk2 version. Screenshot:
![image](https://user-images.githubusercontent.com/1339272/47969719-400d9a80-e07c-11e8-8495-04762efde5f8.png)

On the left there is an app the uses gtk3 theme. On the right, qbittorrent, which uses qt and loads the gtk2 theme.

Looks better in the gtk3 app, but either way, I thinks it should have the same color in both versions.
