### ISSUE TITLE
Xfwm4 Themes Not Present in xfwm4-settings on Fedora 39

### ISSUE THREAD

**Issue by BlindRepublic** [daniruiz/flat-remix-gtk#161]
The Xfwm4 theme for Flat Remix doesn't show up on the settings page on Fedora 39 even though it is present under `/usr/share/themes/` when installed from the repos. 

I'm not sure if this is a packaging issue or something that changed in Xfce.

**Comment by daniruiz** [comment]
The package is outdated and I'm not maintaining it. Just download the themes from here or from gnome-desktop
