### ISSUE TITLE
enable to read out fonts/titles in dark/darkest variants.

### ISSUE THREAD

**Issue by anonymous9097** [daniruiz/flat-remix-gtk#163]
Hey there @daniruiz...
Huge thanks for this awesome theme....
but i am getting an issue regarding night/dark variants of flat-remix theme..I am enable to see titles or fonts as they conflicts with background grey color making it almost impossible to see...
This happens only in dark/darkest variants while light variants perform good in it.I had a request to integrate selection of any title in panel, color should be same with the theme variant..
here i am attaching some screenshot of it.
Hope it will sort out next update.
Thanks
### light variant
![ss1](https://github.com/daniruiz/flat-remix-gtk/assets/83274362/ed5aa380-21f5-4471-96ef-be869963145b)

### dark variant
![ss2](https://github.com/daniruiz/flat-remix-gtk/assets/83274362/f080412b-4027-47fe-aeb7-954dc4a87c0d)
### notification fonts error
![ss3_edited](https://github.com/daniruiz/flat-remix-gtk/assets/83274362/6b656245-4aeb-495a-ae13-99e209c7ed46)

**Comment by daniruiz** [comment]
That's the gnome-shell theme not the gtk one. You're problably using the wrong version of the theme for the version of gnome-shell you have
