### ISSUE TITLE
The new version

### ISSUE THREAD

**Issue by lovemoebius** [daniruiz/flat-remix-gtk#17]
I love your work, the Flat-Remix Dark theme was absolutely fantastic and very professional.I updated to the last version and I'm not a huge fan of it. The white border feels really out of place and the very rounded borders on the buttons don't work well with the rest of the theme.

I know this is free and I shouldn't complain, but still I think it's worth leaving my feedback. Hopefully you'll update it again in the future!

**Comment by daniruiz** [comment]
I've uploaded the new version with the previous dark colors as Flat-Remix-Dark and moved the "full black" version to Flat-Remix-Darkest.
![image](https://user-images.githubusercontent.com/12565871/47898359-db80ee80-de75-11e8-8a68-4ad2745f2adc.png)

**Comment by lovemoebius** [comment]
That's fantastic news, thank you so much.

**Comment by RixzZ** [comment]
It may be too much, but a Darkest version without the white frame would be great. I like the white frame but it only appears in some apps which makes it weird...
