### ISSUE TITLE
Ubuntu ppa not updated

### ISSUE THREAD

**Issue by Old-Knitterhemd** [daniruiz/flat-remix-gtk#18]
As the title says, the ubuntu ppa seems to be the old "new" version.

Using Ubuntu 18.04.

Also having issues with the Gnome theme.

Thanks for the work!

**Comment by daniruiz** [comment]
Give me a break! I uploaded this version to gnome-look to test it but I didn't have time to update the repos. I have to study.

**Comment by Old-Knitterhemd** [comment]
Was not my intention to stress you.
Just wanted to mention.

Thanks again, keep up the good work!
