### ISSUE TITLE
Invisible menu-text on Ubuntu Mate in Cupertino style

### ISSUE THREAD

**Issue by gonzoMD** [daniruiz/flat-remix-gtk#19]
Steps to reproduce:

-install your theme
-choose your theme (light version)
-open mate-tweak and set the Bar settings to Cuperino
-go to the top-bar menu and highlight some menu items

now you see that there is white text on white background and that it is only visible while hovering it.

**Comment by daniruiz** [comment]
I'm closing this issue as it is old and all the themes have been completely redesigned.
If the issue persists, even with the new themes, feel free to reopen it.
