### ISSUE TITLE
Terminal windows don't have borders in Darkest-Solid

### ISSUE THREAD

**Issue by ajruckman** [daniruiz/flat-remix-gtk#20]
In the Flat-Remix-GTK-Darkest-Solid theme, terminal windows don't have borders, which makes it very hard to tell where windows are.

[See picture.](https://i.imgur.com/eOCn9Kj.png)

Is it possible to add a border to terminal windows like other windows have?

**Comment by daniruiz** [comment]
I don't understand why that happens only on x11 because with wayland it works perfectly

**Comment by daniruiz** [comment]
I recommend you installing tilix and python-nautilus to completely replace gnome-terminal
![image](https://user-images.githubusercontent.com/12565871/48716295-4ae93300-ec17-11e8-9041-3e6f76526752.png)

**Comment by daniruiz** [comment]
I've just solved it. Try the new update.
