### ISSUE TITLE
How does Flat-Remix-GTK modify the topbar transparency?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [daniruiz/flat-remix-gtk#21]
How to modify the top menu background color and transparency？
![2018-11-20 08 56 04](https://user-images.githubusercontent.com/12076232/48744454-49188180-eca2-11e8-94d0-15cdfecded4d.png)

**Comment by daniruiz** [comment]
The GTK theme can't modify gnome-shell appearance but by the gnome-shell theme http://github.com/daniruiz/flat-remix-gnome
