### ISSUE TITLE
Alternate Darkest and Darkest-solid without the white border

### ISSUE THREAD

**Issue by yash1610** [daniruiz/flat-remix-gtk#22]
Love the theme but it would be nice to have another option for darkest and darkest-solid that has no white border

**Comment by daniruiz** [comment]
Love it!!
I keep it for next release.
Also a dark version with the border or do I only add the darkest one but without it?

**Comment by RixzZ** [comment]
A dark version with a non-white (greyish) border, might look great. Anyway, I vote for the Darkest without border at least.

**Comment by daniruiz** [comment]
There you have it ;)

**Comment by RixzZ** [comment]
Thanks a lot. I'll try it now.
