### ISSUE TITLE
xfce4 support 

### ISSUE THREAD

**Issue by elswerky** [daniruiz/flat-remix-gtk#25]
plz can you support xfce4 desktop 

when i install this theme on xfce desktop ,, i can choose it from appearance but still i need to choose it from windows manager to theme window (like minimize ,maximize ) with flat remix 

but i don't find it in windows manager theme to choose it 

support it plz 

![window](https://user-images.githubusercontent.com/26687459/50623903-2c1ed180-0f23-11e9-97b6-c26dd6c2618a.jpg)

**Comment by lightoyou** [comment]
Need the same can i help ?

**Comment by daniruiz** [comment]
Done! I've just added XFCE support :+1: 
![VirtualBox_Xubutunu_01_06_2019_00_03_06](https://user-images.githubusercontent.com/12565871/58746496-26d89b00-845f-11e9-82e8-f28ab8d345f8.png)
