### ISSUE TITLE
On Elementary is Perfect! ...But

### ISSUE THREAD

**Issue by AdsonCicilioti** [daniruiz/flat-remix-gtk#26]
A little bit corrections for the beste GTK theme...
In user folder, the breadcrumb section assumes an search field, and placeholder text are dark and not aligned verticaly. See:
![image](https://user-images.githubusercontent.com/6278398/51552737-627faa80-1e58-11e9-9576-2933af88afbf.png)

Only this.. and thanks for the beautiful theme!

**Comment by daniruiz** [comment]
Ups. Didn't see that, thanks for notifying and for the feedback. I'll solve it as soon as possible

**Comment by AdsonCicilioti** [comment]
Ok.. 
just simplifying tasks:

- [ ] Plancheholder text light color on Dark variations
- [ ] Plancheholder text vertical align

An question: The style language is CSS/SASS?
Think i help.. wait

**Comment by AdsonCicilioti** [comment]
how you compile the sass? I want colaborate!
Explain your workflow. Please!

**Comment by hcnhcn012** [comment]
The same issue on my elementary os, it could be perfect after solving this

**Comment by daniruiz** [comment]
It's been a while but I wasn't able to find where's the problem as I wasn't able to find the selector for that placeholder. If anyone can help me it would be great :sweat_smile:

**Comment by daniruiz** [comment]
Finally!!! :tada:  :tada:  :tada:
