### ISSUE TITLE
Please provide Flatpak package so Flatpak applications show correct theme

### ISSUE THREAD

**Issue by NoeelMoeskops** [daniruiz/flat-remix-gtk#28]
Hi,

Could you please provide a Flatpak package for the theme, so that Flatpak applications show the correct theme instead of the default GTK theme (Adwaita for Gnome).

left native application with theme, right Flatpak application that fails to see the theme.
![example (left native application with theme, right Flatpak application that fails to see the theme.](https://user-images.githubusercontent.com/10706939/53099707-9d8fff00-3526-11e9-9ce1-102b59e91dec.png)
For more information please see: [this post](https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html)

**Comment by daniruiz** [comment]
I've been doing some tests and I've seen that if you also install the themes to your local .themes directory Flatpak applications will use it. Elementary themed apps (such as sequeler) will prefer to maintain it's own theme by the way.


![Peek 01-05-2019 11-32](https://user-images.githubusercontent.com/12565871/57012157-6c5a3c00-6c05-11e9-8063-efac190fc73d.gif)

**Comment by NoeelMoeskops** [comment]
interesting. I did `ln -s /usr/share/themes/ ~/.themes` but my flatpak applications still use the default theme. Copying the GTK theme worked tho. Good work :+1:

**Comment by matfantinel** [comment]
Not meaning to reopen this issue, but the method worked for all apps except Geary from Flathub. Geary correctly changes to a flatpak-installed theme like Pop, but not with Flat Remix. Anyone using it to confirm?

**Comment by fsevenm** [comment]
> interesting. I did `ln -s /usr/share/themes/ ~/.themes` but my flatpak applications still use the default theme. Copying the GTK theme worked tho. Good work +1
> It would be even better if there was no manual interaction. Because now when the theme updates you need to manual copy the folder again.

From this, I realized that not everything works with symlink. This saved me hours.
