### ISSUE TITLE
ArchLinux AUR 404

### ISSUE THREAD

**Issue by BERNARDO31P** [daniruiz/flat-remix-gtk#31]
It seems like the package has been removed from the AUR repository. 
Is there any specific reason?

https://aur.archlinux.org/packages/flat-remix-gtk-git/

**Comment by daniruiz** [comment]
Yes. The repo flat-remix-gtk-git has been moved to just flat-remix-gtk as now it will be based on stable updates instead of picking the last change from github.

**Comment by BERNARDO31P** [comment]
Ah alright, thank you very much.

Have a nice weekend!
