### ISSUE TITLE
Spaces on titlebar buttons when aligned on the left

### ISSUE THREAD

**Issue by gaou-piou** [daniruiz/flat-remix-gtk#32]
The left space from the close button on titlebar, when you arrange buttons on the left is very small.

<img src="https://api.pcloud.com/getpubthumb?code=XZoePq7ZYjRliVNLCykh52NDMHJ5fJ3voqeV&linkpassword=undefined&size=920x55&crop=0&type=auto">

**Comment by daniruiz** [comment]
![image](https://user-images.githubusercontent.com/12565871/54852904-85aac700-4cee-11e9-8901-211b66a779f8.png)
When arranged to right it is the same
