### ISSUE TITLE
Perfect theme but with a little issue

### ISSUE THREAD

**Issue by zl3one6** [daniruiz/flat-remix-gtk#33]
Reproduce:
In a light version theme, like Flat-Remix-GTK, use default browser in Ubuntu 18.04, Firefox, open www.bing.com and the text in the input field is dark color, that is normal.

But in a dark version theme, like Flat-Remix-GTK-Dark, use same browser as above, open www.bing.com and the text in the input field is light color, coincided with the background white color, hence user cannot see the text.

**Comment by Dvlnst** [comment]
A workaround:
1) Firefox > about:config
2) Create a new string entry: **widget.content.gtk-theme-override**
3) Set this entry value: **adwaita**

Flat-Remix theme works fine and it fix input field colors.

Kind regards.

**Comment by zl3one6** [comment]
That works!
