### ISSUE TITLE
Path bar style issue

### ISSUE THREAD

**Issue by Dvlnst** [daniruiz/flat-remix-gtk#34]
Hi,

I'm using your theme for a long time actually, but with the last release (installed from source and OpenDesktop.org), the path bar looks awful:
![Screenshot from 2019-03-28 03-07-09](https://user-images.githubusercontent.com/36289254/55124582-014daf00-5107-11e9-94fc-0c3d5dec8ae2.png)

Any idea how to fix it? Thank you for the awesome work!

Requirements:
 - OS: Debian Buster (Testing)
 - Gnome version: 3.30.2

**Comment by daniruiz** [comment]
UUUUgh WTF!!! Looks terrible. Nautilus has changed the pathbar 3 times for last releases and now it's difficult to know if the theme fits them all.
Give me some hours and it'll be fixed.

**Comment by daniruiz** [comment]
Fixed :smile:

**Comment by Dvlnst** [comment]
Thank you very much for all the work!

Kind regards.
