### ISSUE TITLE
How can I set the WM theme to Flat Remix?

### ISSUE THREAD

**Issue by dariusity** [daniruiz/flat-remix-gtk#38]
Hi there, I am running on Manjaro LXQt with Openbox as Windows Manager & GTK2/3 installed. There is just one small hiccup here, would you know how can I switch the Windows Theme to Flat Remix? After I installed Flat Remix it only appeared in Appearance but not for Openbox. Please enlighten me!

**Comment by daniruiz** [comment]
The theme doesn't provide an openbox theme but you could change the window manager to xfwm4 and use its theme.
https://github.com/lxqt/lxqt/wiki/ConfigWindowManagers
