### ISSUE TITLE
Budgie Menu

### ISSUE THREAD

**Issue by algent-al** [daniruiz/flat-remix-gtk#40]
I don't know if this is intentionally or not.
![Budgie-Menu-Black-Space](https://user-images.githubusercontent.com/46356616/55389318-4cb3f300-5535-11e9-9b31-ed29c8d6902d.png)

I think it should be at same color as sub-menu.

**Comment by daniruiz** [comment]
![image](https://user-images.githubusercontent.com/12565871/57980912-b595f280-7a31-11e9-99ca-d84581c97d3b.png)

I've found the solution :smile:
