### ISSUE TITLE
this is what it looks like

### ISSUE THREAD

**Issue by jinfagang** [daniruiz/flat-remix-gtk#41]
![image](https://user-images.githubusercontent.com/21303438/55453620-30848480-560f-11e9-9cdd-42fe82e35912.png)

it seems that,  not like the picture announced...

**Comment by daniruiz** [comment]
Which desktop or linux distribution are you using?

**Comment by jinfagang** [comment]
Ubuntu 16.04, 3 years old maybe, with gnome 2.x, but I want cool like that theme, what should I do

**Comment by daniruiz** [comment]
I think you should update it to a newer Ubuntu. Here is an explanation about how to update ubuntu from 16.04 to 18.04 https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes
Hope it helps :smile:
