### ISSUE TITLE
Why title bar of nautilus changed?

### ISSUE THREAD

**Issue by inzar98** [daniruiz/flat-remix-gtk#45]
![2019-05-13 01-50-48 ekran görüntüsü](https://user-images.githubusercontent.com/4786066/57588751-9f63d000-7521-11e9-822a-cb99ea78651c.png)

I was really like this "https://cn.opendesktop.org/img/c/d/a/f/1a73bf24f1ae8d1570d9b2db88c7193cdf95.png" 

How can I revert to it ?

**Comment by daniruiz** [comment]
I liked it, but It's a bit problematic so it's just being reverted :wink:
