### ISSUE TITLE
Budgie Desktop

### ISSUE THREAD

**Issue by algent-al** [daniruiz/flat-remix-gtk#46]
Some little work is needed. The dot under the application launchers is not visible maybe it is way too down to be visible.
![no dot](https://user-images.githubusercontent.com/46356616/57986679-4f808e00-7a78-11e9-83be-b80d93e2d816.png)

Like this in Qogir Theme.
![dot](https://user-images.githubusercontent.com/46356616/57986681-54454200-7a78-11e9-9cf5-3325c577ec90.png)

OS: Solus Budgie 4.0

**Comment by algent-al** [comment]
Hi! The issue is fixed if I increase the panel size to 45px. So the dots are there but below the screen. I think that the panel should be more compact. I usually have it a 39px.
![settings](https://user-images.githubusercontent.com/46356616/62416754-d50be700-b640-11e9-804f-5a98c34f57f6.png)
![panel45](https://user-images.githubusercontent.com/46356616/62416758-e0f7a900-b640-11e9-9276-626ffb93ae7c.png)

**Comment by daniruiz** [comment]
Just fixed! :wink:
