### ISSUE TITLE
Bug nautilus 3.30.5-stable

### ISSUE THREAD

**Issue by Makoto83** [daniruiz/flat-remix-gtk#47]
Hi thanks a lot this wonderful theme.
but I encounter a random problem that has persisted since

![Light bug transparency](https://i.imgur.com/JpyZp8r.png)
![Dark bug transparency](https://i.imgur.com/BNQV8nt.png)

**Comment by daniruiz** [comment]
What is the problem?

**Comment by Makoto83** [comment]
No transparency top

**Comment by daniruiz** [comment]
'solid' variants are the ones without transparency
