### ISSUE TITLE
Bug nautilus 3.30.5-stable

### ISSUE THREAD

**Issue by Makoto83** [daniruiz/flat-remix-gtk#48]
Well I restart the subject .....
you do not see the pictures below?
I use Flat-Remix-GTK-Yellow-Dark theme and not 'solid'

He has a bug on the images
![Dark bug transparency](https://i.imgur.com/BNQV8nt.png)
![BUG](https://i.imgur.com/tx8WEfR.png)

**Comment by daniruiz** [comment]
That's the way it should work. It is transparent, but a transparent layer over another transparent one makes it more opaque.
![image](https://user-images.githubusercontent.com/12565871/58166791-df962180-7c8a-11e9-864e-4070ebef4d65.png)
