### ISSUE TITLE
[Feature Request] Add a light theme similar to the new Windows Light Theme

### ISSUE THREAD

**Issue by ThatFatPat** [daniruiz/flat-remix-gtk#49]
The current light themes present a completely white interface.
It would be really nice if there could be some intermediate color, such as the light gray shown in the new Windows "Light" theme.

Thanks in advance,
Pat

**Comment by daniruiz** [comment]
I'm sorry but for now there are more than enough variants for me. Each variant makes it more difficult to maintain.
