### ISSUE TITLE
Add a preview.png file to each of the different theme variants.

### ISSUE THREAD

**Issue by LeptoSpira** [daniruiz/flat-remix-gtk#50]
I see the main image, showing me what light, darker, dark, and darkest look like, and I know I want the blue version. So what now? I need to somehow find the difference between:
- [`Normal`](https://github.com/daniruiz/flat-remix-gtk/tree/master/Flat-Remix-GTK-Blue-Darkest)
- [`Solid`](https://github.com/daniruiz/flat-remix-gtk/tree/master/Flat-Remix-GTK-Blue-Darkest-Solid)
- [`No Border`](https://github.com/daniruiz/flat-remix-gtk/tree/master/Flat-Remix-GTK-Blue-Darkest-NoBorder)
- [`Solid` and `No Border`](https://github.com/daniruiz/flat-remix-gtk/tree/master/Flat-Remix-GTK-Blue-Darkest-Solid-NoBorder)

How am I supposed to tell which one I like without downloading and trying each of them?
I suggest when going inside of the theme, you see a preview.png file to check what that specific variant looks like.

**Comment by daniruiz** [comment]
![image](https://user-images.githubusercontent.com/12565871/58592494-def02300-8268-11e9-86b2-21d2a971a751.png)
If I add a picture for each theme I'd have to update them every time I make a huge change. Solid and noBorder variants are explained in the README and I don't think downloading and trying them is that hard.
