### ISSUE TITLE
Unstyled input fields have invisible text on dark theme

### ISSUE THREAD

**Issue by andrewc910** [daniruiz/flat-remix-gtk#52]
- blue dark theme
- open firefox and find an unstyled input text box
    - The text is the same color as the background
    - Working with rails right now so i have plenty of unstyled text boxes

If anyone has a quick fix, that would be awesome. Can't seem to find the proper class in the css file.

**Comment by daniruiz** [comment]
Firefox does some weird things with all dark themes, is a known issue. The only fix for now is to force Adwaita theme in Firefox:
* Navigate to about:config
* Right click and select "New"→"String"
* Enter `widget.content.gtk-theme-override` as the name
* Enter gnome's default gtk theme for the value: "Adwaita"
* Restart Firefox
