### ISSUE TITLE
Plugin's background color issue in Manjaro XFCE panel

### ISSUE THREAD

**Issue by firewolfxda** [daniruiz/flat-remix-gtk#55]
With "Flat-Remix-GTK-Blue-Darkest-Solid-NoBorder" applied
![prb](https://user-images.githubusercontent.com/22277019/60944592-155e9a80-a30b-11e9-8798-09d06bd363c5.png)

With "Matcha-dark-aliz" applied
![fix](https://user-images.githubusercontent.com/22277019/60944611-227b8980-a30b-11e9-9e93-12531448f8ff.png)

Possible fix: https://forum.manjaro.org/t/issues-after-updating-xfce4-packages/37015/9

With "Vertex-Maia-Light-Fix" applied
![fix2](https://user-images.githubusercontent.com/22277019/60944652-37581d00-a30b-11e9-9673-618ff70ef940.png)

**Comment by daniruiz** [comment]
Is it fixed now with the new update?
