### ISSUE TITLE
Resizing titlebar buttons

### ISSUE THREAD

**Issue by anthonyclarka2** [daniruiz/flat-remix-gtk#56]
Hello, this is a very low priority question, I wasn't sure where else to find help.

I'd like to increase the size of all windows' titlebars and minimize/maximize/close buttons. I've been trying to use gtk.css but all I can seem to do is make the titlebar bigger, but nothing changes the buttons. Do you know if it's possible to do this via css? This is my gtk.css file so far:

`~/.config/gtk-3.0/gtk.css`

`headerbar.titlebar {`
`  min-height: 64px;`
`}`
                                                                                
`headerbar button.titlebutton.close,`
`headerbar button.titlebutton.maximize,`
`headerbar button.titlebutton.minimize,`
`.titlebar button.titlebutton.close,`
`.titlebar button.titlebutton.maximize,`
`.titlebar button.titlebutton.minimize {`
`  min-height: 48px;`
`  min-width: 48px;`
`}`

**Comment by daniruiz** [comment]
You need to add ` background-size: 100%` or the button image won't scale. Anyway if you change the button's size you'll need to modify the assets and make them bigger or the buttons will look blurry.
