### ISSUE TITLE
Plugin's background color issue in Manjaro XFCE panel

### ISSUE THREAD

**Issue by firewolfxda** [daniruiz/flat-remix-gtk#57]
With "Flat-Remix-GTK-Blue-Darkest-Solid-NoBorder" applied

![prb](https://user-images.githubusercontent.com/22277019/60943976-62417180-a309-11e9-869b-45ef9d1a3a88.png)

With "Matcha-dark-aliz" applied

![fix](https://user-images.githubusercontent.com/22277019/60944048-8a30d500-a309-11e9-897e-f7bfd3b9092c.png)

Possible fix: https://forum.manjaro.org/t/issues-after-updating-xfce4-packages/37015/9

**Comment by daniruiz** [comment]
Duplicated #55
