### ISSUE TITLE
Google chrome has grey border

### ISSUE THREAD

**Issue by aquaductape** [daniruiz/flat-remix-gtk#62]
Google chrome has a noticeable grey border around the window. Shows grey border on all Blue theme variations. Here's a screenshot in comparison to other applications.

![alt text](https://i.imgur.com/oa95Q7t.png)

**Comment by daniruiz** [comment]
That border is added by default by chrome and can not be changed. Chrome doesn't use the theme itself but gets some colors from it to better fit with the desktop.

**Comment by ikeofkc** [comment]
Please star this issue if you happen upon this closed issue and are annoyed by this in chrome https://github.com/daniruiz/flat-remix-gtk/issues/62
