### ISSUE TITLE
[Budgie] Applet icon get shrinket

### ISSUE THREAD

**Issue by algent-al** [daniruiz/flat-remix-gtk#63]
Hi! I use Solus Budgie. 
Tried this theme again and I see that there is a little issue.
When hovering the mouse over the applets like "Show Desktop" or "Raven", these i cons get shrinked to the right. The panel looks like it is moving to the right.

Made some screenshots:
![no-hover](https://user-images.githubusercontent.com/46356616/64125018-e283d080-cda8-11e9-8786-7a90e1e96d16.png)
![show-desktop](https://user-images.githubusercontent.com/46356616/64125022-e7488480-cda8-11e9-952b-00930d15d57f.png)
![raven](https://user-images.githubusercontent.com/46356616/64125030-eadc0b80-cda8-11e9-87aa-e2adeafaa680.png)

The images are at same size 300x40px at same place.

**Comment by algent-al** [comment]
Hi! I made gif to make this bug more visible.

![flat-remix-panel](https://user-images.githubusercontent.com/46356616/77434278-e7f64600-6de0-11ea-8c42-834adf1e757b.gif)


The issue still present in latest version 20191224.

**Comment by daniruiz** [comment]
Thanks! I've wanted to fix that bug for a while but my time is really limited lately.
Someday I'll fix it, I promise :sweat_smile:

**Comment by algent-al** [comment]
Now it looks very cool. Thank you for the fix.
