### ISSUE TITLE
Scroll bar oversized in gnome terminal

### ISSUE THREAD

**Issue by philong6297** [daniruiz/flat-remix-gtk#64]
Ubuntu 19.04
![image](https://user-images.githubusercontent.com/29605147/64268891-23bfe000-cf63-11e9-89d7-6cf132611f3a.png)

**Comment by daniruiz** [comment]
That's an ubuntu issue, it also happens with the vanilla gtk theme 
![image](https://user-images.githubusercontent.com/12565871/69006572-1777dc00-0931-11ea-9261-b2361d68e84c.png)
