### ISSUE TITLE
darkest yellow theme unreadable selected text in some applications

### ISSUE THREAD

**Issue by damscal** [daniruiz/flat-remix-gtk#66]
Terrific theme suite, thanks for sharing. Darkest yellow is my favorite, but at times in some application (e.g. in ccsm, or during Alt+Tab in xfce) the front font colour of selected text remains white while it is highlighted with a bright yellow background, resulting in unreadable text. An easy fix would be to change the selected text background to a darker shade of yellow, e.g. d17000

**Comment by daniruiz** [comment]
This was already fixed ;) and I forgot to close the issue
