### ISSUE TITLE
Tight elements on file selector

### ISSUE THREAD

**Issue by gnumoksha** [daniruiz/flat-remix-gtk#69]
Hi, thank you for Flat-Remix! Is the best GTK and Gnome shell theme!

So, should this screen be like this?
![Screenshot from 2019-10-31 14-50-31](https://user-images.githubusercontent.com/696797/67972792-20a54100-fbee-11e9-8315-465f8cf6cadd.png)

I would like more space between left bar elements, breadcrumb and files itself. Is it possible?

I'm using Flat-Remix-GTK-Blue-Darker.

**Comment by daniruiz** [comment]
I think you are using an outdated GTK version. Which DE are you using?

**Comment by gnumoksha** [comment]
Gnome 3.34.1.

I think this screen occurs only with Slack (installed from snap store) and since I already had many confirmed problems with Slack, I will close this issue.
