### ISSUE TITLE
Custom color ?

### ISSUE THREAD

**Issue by KushagraKarira** [daniruiz/flat-remix-gtk#70]
Not a issue, but a query "**How do i get a custom color for this theme**", i need a kinda pink color to match my desktop wallpaper.

**Comment by daniruiz** [comment]
You can modify the `src/build.sh` script and replace one of the colors inside VARIANT_COLORS (the first one for example corresponds to the blue variant)

You will need sass installed to generate the new themes. Then run `make build-sass` and it will generate all the variants for you :wink: 

Hope that helped!
