### ISSUE TITLE
Request for support of Flatpaks

### ISSUE THREAD

**Issue by ShashikanthChill** [daniruiz/flat-remix-gtk#71]
Flatpak apps doesn't support themes (uses adwaita as default) unless, if same theme is used in gnome-shell and installed as flatpak too. Currently there are around 25 themes that can be installed as flatpaks. Can flat-remix-gtk provide support for flatpaks too so that they can be applied as theme for flatpak apps?

**Comment by daniruiz** [comment]
https://github.com/daniruiz/flat-remix-gtk/issues/28

Flatpak apps can also work with the theme if it is installed to your local `~/.themes` directory.
Right now I don't have time to support flatpak packaging but I'll maintain this issue opened, just as a reminder for future updates

**Comment by daniruiz** [comment]
I close this, as themes work just fine inside ~/.themes so I don't see the point of creating a new package only for this
