### ISSUE TITLE
Closing nautilus resize window vertically

### ISSUE THREAD

**Issue by akiirui** [daniruiz/flat-remix-gtk#72]
Like [Closing nautilus (files) in GNOME 3.22-3.24.1 resize window vertically](https://github.com/numixproject/numix-gtk-theme/issues/667)

Close the nautilus window, `/org/gnome/nautilus/window-state/initial-size` height are `-4px`.

Cannot reproduce with Adwaita GTK theme.

- GTK theme: Flat-Remix-GTK-Blue 20191116
- Nautilus version: 3.34.2

**Comment by daniruiz** [comment]
I can reproduce this with Adwaita, so it isn't the theme's fault
