### ISSUE TITLE
Background color for Xfce panel 

### ISSUE THREAD

**Issue by gandriyko** [daniruiz/flat-remix-gtk#74]
Is it possible to make botton panel in xfce in dark color for Flat-Remix-GTK-Blue (same as for  Flat-Remix-GTK-Blue-Darkest)
I use icons: Flat-Remix-Blue (same issue for light and dark variant)
![a2](https://user-images.githubusercontent.com/1176487/70867759-99374580-1f81-11ea-9cab-f370e02710ca.png)

ArchLinux, latest flat-remix-gtk 20191214-1

**Comment by gsbhasin123** [comment]
You can change the color somewhere in panel settings.
