### ISSUE TITLE
Flaws that only exist in dark variants

### ISSUE THREAD

**Issue by notcdk** [daniruiz/flat-remix-gtk#75]
Hello, I want to say I love your themes!
In comparison to the white theme there are some flaws that happen on both dark and darkest variants
I'm on Fedora 31 with gnome 3.34.3 with default setup and I own a 1920x1080 display

This looks okay:
![Screenshot from 2020-01-20 14-11-08](https://user-images.githubusercontent.com/28454922/72730491-c33be300-3b91-11ea-8ff6-0e42ab37175e.png)

Zoom in and you will see some darker pixels around for no reason ( you should be able to see it without zooming in):
![Screenshot from 2020-01-20 14-22-05](https://user-images.githubusercontent.com/28454922/72730514-cc2cb480-3b91-11ea-89c1-c114acb9aa91.png)

In gnome software there persists the same issue with search button and also when you click the 3 dots on the right, in addition this happens to the tabs (i could say to most widgets with very rounded corners):

White
![Screenshot from 2020-01-20 14-12-27](https://user-images.githubusercontent.com/28454922/72730886-b5d32880-3b92-11ea-8f32-40dbf24f9e48.png)

Darkest
![Screenshot from 2020-01-20 14-22-25](https://user-images.githubusercontent.com/28454922/72730905-c2f01780-3b92-11ea-8b24-97d8a090832c.png)

The search bar rounded corners look very pixelated on dark themes which is not visible at all on white theme.

I would also suggest to make the text look just a little bit darker on darkest theme:
![Screenshot from 2020-01-20 14-17-36](https://user-images.githubusercontent.com/28454922/72731082-35f98e00-3b93-11ea-9539-f1286e491b74.png)
![Screenshot from 2020-01-20 14-17-19](https://user-images.githubusercontent.com/28454922/72731150-5c1f2e00-3b93-11ea-9e32-31155867b757.png)
![Screenshot from 2020-01-20 14-11-28](https://user-images.githubusercontent.com/28454922/72731096-3db93280-3b93-11ea-872f-0d4bf5356fe7.png)
![Screenshot from 2020-01-20 14-21-58](https://user-images.githubusercontent.com/28454922/72731103-40b42300-3b93-11ea-9c7f-0f1d9f7f881a.png)

Thanks for your work!
I also packed the screenshots to a zip if for some reason github did
 something to the screenshots here.

[screenshots.zip](https://github.com/daniruiz/flat-remix-gtk/files/4086440/screenshots.zip)

**Comment by daniruiz** [comment]
Hi!

Thank you for the nice feedback :wink: 
Unfortunately, there's nothing I can do to fix these issues. The issue with rounded corners in the dark variant is due to the way gtk is rendered.
