### ISSUE TITLE
Dark text color on autocomplete in chrome.

### ISSUE THREAD

**Issue by alexd73** [daniruiz/flat-remix-gtk#77]
Hello!
Help me fix this bug please.
![image](https://user-images.githubusercontent.com/1692056/73611971-aa531900-45f8-11ea-8fcf-4377f3a0d1c1.png)

**Comment by ColinEspinas** [comment]
Hey I have the same problem in the blue darker variant.

![image](https://user-images.githubusercontent.com/30630375/79217341-00d9a080-7e4f-11ea-9dff-ec00f9ed67e3.png)
