### ISSUE TITLE
Respect UI font setting

### ISSUE THREAD

**Issue by ChiDal** [daniruiz/flat-remix-gtk#80]
gnome-shell 3.36 has been released which respects the ui font set using gnome-tweaks. Please add support for this. (It works when the shell theme is set to default)(Compare 2nd and 3rd screenshots)
![image](https://user-images.githubusercontent.com/36493671/76168722-357c7d00-616a-11ea-9995-0fd0be081431.png)
![Screenshot from 2020-03-08 23-58-34](https://user-images.githubusercontent.com/36493671/76168792-bf2c4a80-616a-11ea-8029-87638682e83d.png)
![Screenshot from 2020-03-08 23-58-46](https://user-images.githubusercontent.com/36493671/76168795-c2273b00-616a-11ea-8c8e-87ec26118fa4.png)

**Comment by daniruiz** [comment]
I know about this change, I just don't have time right now.
This is a flat-remix-gnome issue by the way

**Comment by ChiDal** [comment]
> I know about this change, I just don't have time right now.
ah no probs.

> This is a flat-remix-gnome issue by the way
This is a change in the shell right?

**Comment by daniruiz** [comment]
Yes, this is a change in the gnome-shell theme
