### ISSUE TITLE
gnome 3.36 gedit current line highlight is not styled correctly

### ISSUE THREAD

**Issue by zeparu** [daniruiz/flat-remix-gtk#83]
![grafik](https://user-images.githubusercontent.com/21054889/77822133-3e6cc880-70f0-11ea-9bb3-cccbc59abdfb.png)
im pretty sure this applies to all dark themes out there, all that i tested have the current line highlighted in a bright color

**Comment by daniruiz** [comment]
Change gedit's color-scheme to a dark one. Here you can find mines https://github.com/daniruiz/dotfiles
they are inside `'/.local/share/gtksourceview-4/styles`

**Comment by zeparu** [comment]
if i choose one of the custom themes, it will work, but using certain color schemes in gedit, that inherit certain colors from gtk theme (or maybe even gnome shell theme), like "classic" or "tango", the screenshot will happen
this is classic 
![grafik](https://user-images.githubusercontent.com/21054889/77822787-2e57e780-70f6-11ea-961a-0d8d26a131df.png)
this is solarized 
![grafik](https://user-images.githubusercontent.com/21054889/77822796-42034e00-70f6-11ea-8299-e1b0b5e11c7e.png)

**Comment by daniruiz** [comment]
That is not posible, if you use Adwaita dark it has the same issue
![image](https://user-images.githubusercontent.com/12565871/77823186-6f053000-70f9-11ea-934c-133038a7c6e7.png)

**Comment by zeparu** [comment]
ok, than its not a bug with themes, but a bug with this new version of gedit

**Comment by daniruiz** [comment]
It's been always that way
