### ISSUE TITLE
White elements in dark theme

### ISSUE THREAD

**Issue by PitcherTear22** [daniruiz/flat-remix-gtk#84]
Since the update to 3.36 (I think), some parts are white
Tilix terminal titlebar:
![tilix](https://user-images.githubusercontent.com/36493671/78387428-d70eb700-75ce-11ea-8b3b-2e65af56e53a.png)
[Fragments](https://gitlab.gnome.org/World/Fragments):
![fragments](https://user-images.githubusercontent.com/36493671/78387527-08878280-75cf-11ea-8ea9-06569d51fbaa.png)

**Comment by daniruiz** [comment]
Weird, I'm not having that issue on :thinking: 
![image](https://user-images.githubusercontent.com/12565871/78397893-582b7580-75f2-11ea-8255-35bd9b8d82de.png)

**Comment by PitcherTear22** [comment]
I even tried installing it again

**Comment by PitcherTear22** [comment]
Solved by [this](https://www.reddit.com/r/archlinux/comments/f6tf1o/certain_gtk_elements_are_not_themedstatic_colour/fib1r44/)

Sorry

**Comment by daniruiz** [comment]
Awesome! thank you :wink:  as some people where facing the same issue on kali and didn't know how to fix it
