### ISSUE TITLE
Styling lost for Dialog panels in gnome 3.36? 

### ISSUE THREAD

**Issue by The-Humble-Fool** [daniruiz/flat-remix-gtk#85]
![image](https://user-images.githubusercontent.com/23189529/79103020-7aa75680-7d89-11ea-8837-9e82aa545ece.png)
![image](https://user-images.githubusercontent.com/23189529/79103179-c35f0f80-7d89-11ea-87f6-e5f21a056fc2.png)

Previously dialog panels used to have white and red buttons and had flat LAF.  In Gnome 3.36, dialog panels doesn't seem to have flat LAF and looks like Adwaita's LAF. 

I tried uninstalling and reinstalling theme too.  I don't know if anyone else is having this issue.

**Comment by daniruiz** [comment]
Not an issue, the theme was completely redesigned for gnome 3.36 so I changed some things from the previous versions (using the vanilla theme as a reference)
