### ISSUE TITLE
Help with changing the colors of the theme

### ISSUE THREAD

**Issue by yash1610** [daniruiz/flat-remix-gtk#86]
Hey, I have been using your theme for a few years now and I have loved it all this time. You even added the noborder option two years ago when I suggested it. Since then the Darkest-solid-noborder has been my only theme ever. 

Lately though I have been having a lot of difficulty visually speaking due to the high contrast of the theme, and I have started to use the [Materia-Dark / Adwaita-Dark](https://github.com/nana-4/materia-theme) theme and have found the color scheme more comfortable for my eyes. But I really really prefer the look of the flat-remix theme and thus want to keep using it. 

Would you please be kind enough to make a version of the theme with Materia-Dark / Adwaita-Dark for me OR help me to make a custom version like that?

P.S I have tried changing the color scheme to the best of my abilities, the outcome wasn't great, the file explorer was weirdly transparent and other things didn't change. :/ https://imgur.com/a/Eo2WnLO

**Comment by daniruiz** [comment]
Sorry, but I can't create a variant for everyone :disappointed:
