### ISSUE TITLE
Transparent stripes while scrolling when used in Cinnamon

### ISSUE THREAD

**Issue by Tygrain** [daniruiz/flat-remix-gtk#88]
![Screenshot 2020-05-02 04-06-23](https://user-images.githubusercontent.com/50624811/80851460-a4d29280-8c2a-11ea-8efc-2ae5a847e548.png)
![Screenshot 2020-05-02 04-06-57](https://user-images.githubusercontent.com/50624811/80851469-abf9a080-8c2a-11ea-83e4-1c5447d43ec2.png)
![Screenshot 2020-05-02 04-08-09](https://user-images.githubusercontent.com/50624811/80851474-b025be00-8c2a-11ea-9423-908c991e6479.png)

**Comment by daniruiz** [comment]
Not a bug

**Comment by Tygrain** [comment]
Sorry, but how can I fix this? In standard themes and Adapta, I did not see such strips, so this is not a Cinnamon bug
