### ISSUE TITLE
Distro

### ISSUE THREAD

**Issue by lukeeey** [daniruiz/flat-remix-gtk#9]
What linux distro is used in the screenshots in the README?

**Comment by daniruiz** [comment]
At the time I'm using fedora but it also works fine on arch and the latest ubuntu

**Comment by trompx** [comment]
Hey @daniruiz, I am using Mint 19.1 cinnamon, in the themes GUI, the Flat Remix theme only appears in "Controls" so I have nemo file manager themed but doesn't appear in "Desktop" so the bottom taskbar is not themed. Is there anything to do?
Thanks for it anyway, it is sublime!
