### ISSUE TITLE
Transparent stripes while scrolling when used in Cinnamon

### ISSUE THREAD

**Issue by Tygrain** [daniruiz/flat-remix-gtk#90]
> Not a bug

_Originally posted by @daniruiz in https://github.com/daniruiz/flat-remix-gtk/issues/88#issuecomment-622647434_
Sorry to open this topic again, but how can I fix this? In standard themes and Adapta, I did not see such strips, so this is not a Cinnamon bug

**Comment by daniruiz** [comment]
Yes you can... I don't want to be mean but right now I don't have the time to figure out where that change was. Arc theme has that stripes too
Open the theme's css file and find something like 'border: .. .dashed' or similar

**Comment by Tygrain** [comment]
> Yes you can... I don't want to be mean but right now I don't have the time to figure out where that change was. Arc theme has that stripes too
> Open the theme's css file and find something like 'border: .. .dashed' or similar

Thank you for your replyThank you for your reply
