### ISSUE TITLE
Snap Store Has No Theme

### ISSUE THREAD

**Issue by elucidsoft** [daniruiz/flat-remix-gtk#92]
This is related to issue https://bugs.launchpad.net/snap-store/+bug/1867417

The beta channel mentioned in that thread does not work, but in any case the 'fix' they have is for it to fallback on the AdWaita theme.

**Comment by daniruiz** [comment]
Yes, known issue
:man_facepalming: what is the point of Ubuntu moving all their apps to snaps if they don't properly integrate with the rest of the desktop
For now, the only way of fixing it would be creating the snap version of this theme. LOL! just for a theme?

**Comment by daniruiz** [comment]
My suggestion, replace all snap apps with normal apt ones
`snap list` `snap remove <app>`
Or just use POP OS!

I'm closing this issue as it is not the theme's fault that ubuntu wanted to do everything they're only way :disappointed: I don't have time to make a snap theme, sorry
