### ISSUE TITLE
Compact GTK windows title height

### ISSUE THREAD

**Issue by renatomefi** [daniruiz/flat-remix-gtk#93]
Would be amazing to get thinner title bars for the windows, something that would look nice with the fullpanel gnome variant!

![image](https://user-images.githubusercontent.com/823634/82369867-f4310500-9a17-11ea-9649-e06a70744d08.png)

![image](https://user-images.githubusercontent.com/823634/82370058-38bca080-9a18-11ea-839a-ecafa1adbbb5.png)

Have you considered that? 

Thanks so much for the great themes, has been a while the gnome desktop world has seen something so well crafted, congratulations!

**Comment by daniruiz** [comment]
Thank you for the good vibes :wink: 
Unfortunately the headerbar needs to be high enough to fit the buttons, as buttons are the same height inside and outside the headerbar. So, in order to reduce it, I'd need to make all widgets smaller.
Nice suggestion anyway :+1:
