### ISSUE TITLE
Causing crash on Cinnamon

### ISSUE THREAD

**Issue by tim77** [daniruiz/flat-remix-gtk#94]
Hello. Seems like `flat-remix-gtk` incompatible with Cinnamon DE and may cause crash. Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1832152

Version of package: `20191224`
Distro: `Fedora 32`
Desktop environment: `Cinnamon`

**Comment by daniruiz** [comment]
Sorry but I can't read the bug on bugzilla, could you please describe the issue here?

**Comment by tim77** [comment]
Sorry, the title is:

__[abrt] cinnamon: wrapped_gobj_toggle_notify(gpointer, GObject*, gboolean)(): cinnamon killed by SIGTRAP__

```
Version-Release number of selected component:
cinnamon-4.4.8-7.fc32

Additional info:
reporter:       libreport-2.12.0
backtrace_rating: 4
cgroup:         0::/user.slice/user-1000.slice/session-2.scope
cmdline:        cinnamon --replace
crash_function: wrapped_gobj_toggle_notify(gpointer, GObject*, gboolean)
executable:     /usr/bin/cinnamon
journald_cursor: s=e296bae5e5f941be979dec66020f1d5d;i=3fde;b=0892aa80b16f449d867a78c33af08938;m=12144f584;t=5a4f635660d51;x=ade810112cfa399c
kernel:         5.6.8-300.fc32.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000
```

> Looks like the theme isn't compatible with cinnamon

```
May 06 13:34:11 localhost.localdomain /usr/libexec/gdm-x-session[18305]: Cinnamon warning: Failed to load theme "Flat-Remix-GTK-Darkest-Solid-NoBorder": Line 130 character 1: No frame style set for window type "normal" in theme "Flat-Remix-GTK-Darkest-Solid-NoBorder", add a <window type="normal" style_set="whatever"/> element
```

**Comment by daniruiz** [comment]
I'm closing this issue as it is old and all the themes have been completely redesigned.
If the issue persists, even with the new themes, feel free to reopen it.
