### ISSUE TITLE
Crashing inkscape

### ISSUE THREAD

**Issue by KushagraKarira** [daniruiz/flat-remix-gtk#95]
The actual problem is there are constant crashes in inkscape while using the theme and also some scaling issues.

![Screenshot from 2020-05-29 16-34-38](https://user-images.githubusercontent.com/36698785/83323959-a1f5ac80-a27f-11ea-8edd-fdbbe33e9d69.png)

I've tried the adwait-dark ( gnome default theme ) and somehow no craashes afterwards.

Running Debian Testing - gnome 3.36, Inkscape 1.0

**Comment by daniruiz** [comment]
I think this is just a casualty. Inkscape sometimes suffer from instability and breaks but that has nothing to do with the theme you are using
