### ISSUE TITLE
Ubuntu Software turns transparent

### ISSUE THREAD

**Issue by Diadochokinetic** [daniruiz/flat-remix-gtk#96]
Hello,

today I noticed that my Ubuntu Software Application has a transparent background when using the theme (see attachment). 

![Screenshot from 2020-06-04 21-46-49](https://user-images.githubusercontent.com/45292173/83803628-365f7500-a6ad-11ea-86fa-25df30ddef3f.png)

This does not happen with the default yaru theme.

I am on Ubuntu 20.04 with the 5.4.0-31-generic kernel. The theme is in /usr/share/themes and selected via gnome-tweaks. I use Flat-Remix-GTK-Blue-Dark-Solid. Other applications work fine with the theme.

Regards,
Fabian

PS: This is my first GitHub issue, pls tell me if you need further information.

**Comment by daniruiz** [comment]
Hi!
Si known issue :cry: Unfortunatelly ubuntu decided to replace most of their apps with snap packages, and for snaps the only way to support a theme is to install it as a snap. I don't have the time to create a snap package and having to install the theme twice sounds like a really bad solution anyway.

So my suggestion would be to replace the snap packages with regular apt ones.
* show packages `snap list`
* remove package `snap remove`

**Comment by Diadochokinetic** [comment]
Hi, 

thank you for that information. I was not aware that snap packages interfere with gtk themes. I try to avoid snap packages anyway. I am used to apt and I like it. I rarely use the GUI App. Just the one time I did, I encountered the issue.

I removed the snap-store and `sudo apt install gnome-store`. This solved the issue. I checked all my other applications and everything else works fine. 

Do you know whether apt packages will be as available in the future as snap packages? Because it would be very sad if we couldn't use all these nice custom themes anymore. I really appreciate the work people put in that.

PS: As I mentioned earlier, this is my first GitHub Issue. Should I close it now?
