### ISSUE TITLE
flatpak support

### ISSUE THREAD

**Issue by sp1ritCS** [daniruiz/flat-remix-gtk#99]
I know there have been a few request's for flatpaks in the past
* https://github.com/daniruiz/flat-remix-gtk/issues/28
* https://github.com/daniruiz/flat-remix-gtk/issues/71
and @daniruiz  just said put it into the `~/.themes`. And while that is a solution, I don't think that it's a good one. (System/User separation etc.)

That's why I've ~~bundled all Flat-Remix-GTK themes~~ created a tool to bundle all Flat-Remix-GTK themes as flatpak packages.

[github.com/sp1ritCS/flatpak_flat-remix-gtk](https://github.com/sp1ritCS/flatpak_flat-remix-gtk)

---

I haven't pushed them to [github.com/flathub/flathub/](https://github.com/flathub/flathub/) yet, because
1. Did I do something wrong (License, etc.) @daniruiz pls check
2. Is it a smart Idea to push all 40 variations of Flat-Remix-GTK as separate themes to flathub (I've looked at other themes, and the also package different variations as different themes, but in most cases they have no more that 4 variations). Might ask flathub staff on irc at some point.

**Comment by daniruiz** [comment]
Uuuh! This is great! :tada: :partying_face:  
My main issue is that I didn't have the time to package it for flatpak, but if you are able to do it I'm totally okay with it. Fell free to package and push it to flathub.
About the theme variations, maybe you could package them per color theme.

**Comment by sp1ritCS** [comment]
So, as you might be able to see, I've decided to push all packages separately and automate that a but using github-cli.
Reason I did it seperatly is because @barthalion on the flathub discourse said so.
https://discourse.flathub.org/t/packaging-multiple-variations-of-a-gtk-theme/623

**Comment by daniruiz** [comment]
Hi there!

Thank you so much for creating the flatpak package :wink: 
There have been some improvements in the theme for gnome 3.38 and I wonder if you could update the packages with the lastest changes

**Comment by sp1ritCS** [comment]
Updated from 20201018 to 20201106

In a few hours they should be built and available to update

**Comment by daniruiz** [comment]
Awesome, Thank you :hugs:

**Comment by daniruiz** [comment]
I'm closing this as it's already done ;)
